server:
  port: 9090

bot:
  name: GiftBot
  token:
  owner:

spring:
  application:
    name: GiftBot
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:postgresql://localhost:6432/gift-bot-db
    driver-class-name: org.postgresql.Driver
    username: user
    password: user